# 10. Exception_2

- try, catch, finally
    - try → 정상 로직 실행
    - catch → exception 잡아서 로직 복구
    - finally → try, catch 후 throws전 어떤 일이 있어도 실행되는 로직
- 예외 계층
    - 예외도 객체 → 부모를 상속하는 자식을 만들어서 더 세밀하게 예외 처리 가능
    - 물론 catch를 할때 부모 객체를 잡아도 상관 없음
    - catch 시 하나의 try 아래에 여러개의 catch를 할 수 있음
        - 다만 catch는 순서대로 진행됨 → 부모 exception을 위에 선언하고 자식 exception을 밑에 선언하면 부모 exception에서 다 잡기 때문에 컨트롤 불가능
    - 한번의 catch 시 | 를 사용하여 여러개의 exception catch 가능 → 다만 이 경우 공통된 기능만 사용 가능. 각자 추가 선언된 기능은 사용 불가능.
- 예외처리 실무
    - 실무에서는 처리가 가능한 예외보다 처리 불가능한 예외가 더 많이 발생함 (ex. 네트워크 오류, 정전, 랜선 고장 등등)
        - 체크 예외를 사용하는 경우 처리할 수도 없는 예외를 개발자가 하나하나 선언을 해줘야 한다.
            - 체크예외에서 throws Exception을 할 수는 있으나 이 방법은 정말 중요한 예외도 한번에 던지기 때문에 사용하면 안된다.
    - 예전엔 컴파일러가 체크해주는 체크예외를 더 많이 사용했으나 요즘엔 위의 이유로 언체크 예외를 더 많이 사용함 → 자바, 스프링에서 제공하는 라이브러리나 오픈소스 라이브러리도 언체크 예외를 더 많이 사용
        - 실제 처리할 수 있는 예외만 catch하고 나머지 처리가 불가능한 예외에 대해서는 선언 없이 던질 수 있기 때문
            - 이러한 처리가 불가능한 예외들은 로그 파일 작성 등으로 공통으로 예외 처리를 해야함
- try-with-resources
    - 애플리케이션에서 외부 자원을 사용하는 경우 반드시 해제를 해야함.
        - 이 경우 finally의 사용이 필수
    - 자바 7 부터는 try with resources라는 기능을 도입했는데 해당 기능은 try가 끝나면 자동으로 close 해주는 AutoCloseable 를 상속받아 사용하면 됨.
        - AutoCloseable 안에 있는 close() 메서드를 오버라이딩해서 사용하면 finally를 사용할 필요 없이 try 후 catch 이전에 finally에 있던 메서드를 사용할 수 있음
        - try with resources 구문은 try (Resource resource = new Resource()) {…} 형식으로 사용 가능. → try 안에 사용할 자원을 명시해야함.
    - 물론 이 기능은 catch 없이도 사용이 가능함 → 예외 터지면 close() 후 던짐.
    - 장점
        - 리소스 누수 방지 : finally를 실수로 누락하더라도 무조건 close() 실행
        - 코드 간결성 및 가독성 향상 : finally가 없어도 해당 기능이 동작하기 때문에 코드가 간결해지고 가독성이 좋아짐
        - 스코프 범위 축소 : 리소스로 사용되는 변수의 스코프가 try안으로 한정되기 때문에 유지보수 쉬워짐
        - 신속한 자원 해제 : 기존엔 try → catch → finally 순으로 catch이후에 자원해제가 되었지만 이 기능은 try → (자원 해제) → catch 순으로 자원 해제가 더 신속하다.